#ifndef _SOUND_MAPPING_H
#define _SOUND_MAPPING_H


#define SELECTIONBUTTON_WAV                                           0
#define SELECTIONBUTTON_WAV_LENGTH                                    41
#define COUNTDOWN_WAV                                                 1
#define COUNTDOWN_WAV_LENGTH                                          254
#define BUTTONFEEDBACK_WAV                                            4
#define BUTTONFEEDBACK_WAV_LENGTH                                     62
#define ENDING_WAV                                                    5
#define ENDING_WAV_LENGTH                                             800
#define MAINTHEME_L_WAV                                               6
#define MAINTHEME_L_WAV_LENGTH                                        13217
#define MAINTHEME_LS_WAV                                              7
#define MAINTHEME_LS_WAV_LENGTH                                       13217
#define MAINTHEME_R_WAV                                               8
#define MAINTHEME_R_WAV_LENGTH                                        13217
#define MAINTHEME_RS_WAV                                              9
#define MAINTHEME_RS_WAV_LENGTH                                       13217
#define NODE0_WAV                                                     10
#define NODE0_WAV_LENGTH                                              83
#define NODE1_WAV                                                     11
#define NODE1_WAV_LENGTH                                              45
#define NODE2_WAV                                                     12
#define NODE2_WAV_LENGTH                                              53
#define NODE3_WAV                                                     13
#define NODE3_WAV_LENGTH                                              47
#define NODE4_WAV                                                     14
#define NODE4_WAV_LENGTH                                              95
#define NODE5_WAV                                                     15
#define NODE5_WAV_LENGTH                                              77
#define NODE6_WAV                                                     16
#define NODE6_WAV_LENGTH                                              40
#define NODE7_WAV                                                     17
#define NODE7_WAV_LENGTH                                              97
#define BONUSSOUND_WAV                                                18
#define BONUSSOUND_WAV_LENGTH                                         80
#define LIGHTGRABBERBACKGROUNDMUSIC_WAV                               19
#define LIGHTGRABBERBACKGROUNDMUSIC_WAV_LENGTH                        4800
#define LIGHTGRABBERBACKGROUNDMUSIC_BONUS_WAV                         20
#define LIGHTGRABBERBACKGROUNDMUSIC_BONUS_WAV_LENGTH                  999
#define LG_END_WAV                                                    21
#define LG_END_WAV_LENGTH                                             65
#define BALL_SERVE_WAV                                                31
#define BALL_SERVE_WAV_LENGTH                                         68
#define BALL_HIT_WAV                                                  32
#define BALL_HIT_WAV_LENGTH                                           24
#define BALL_BOUNCE_WAV                                               33
#define BALL_BOUNCE_WAV_LENGTH                                        10
#define ZIGZAGSFX1_WAV                                                34
#define ZIGZAGSFX1_WAV_LENGTH                                         74
#define ZIGZAGSFX2_WAV                                                35
#define ZIGZAGSFX2_WAV_LENGTH                                         69
#define ZIGZAGSFX3_WAV                                                36
#define ZIGZAGSFX3_WAV_LENGTH                                         60
#define ZIGZAGSFX4_WAV                                                37
#define ZIGZAGSFX4_WAV_LENGTH                                         59
#define ZIGZAGSFX5_WAV                                                38
#define ZIGZAGSFX5_WAV_LENGTH                                         59
#define ZIGZAGSFX6_WAV                                                39
#define ZIGZAGSFX6_WAV_LENGTH                                         60
#define ZIGZAGSFX7_WAV                                                40
#define ZIGZAGSFX7_WAV_LENGTH                                         55
#define ZIGZAGSFX8_WAV                                                41
#define ZIGZAGSFX8_WAV_LENGTH                                         65
#define ZIGZAGSFX9_WAV                                                42
#define ZIGZAGSFX9_WAV_LENGTH                                         60
#define ZIGZAGSFX10_WAV                                               43
#define ZIGZAGSFX10_WAV_LENGTH                                        59
#define ZIGZAGBACKGROUNDMUSIC_A_WAV                                   44
#define ZIGZAGBACKGROUNDMUSIC_A_WAV_LENGTH                            4591
#define ZIGZAGBACKGROUNDMUSIC_B_WAV                                   45
#define ZIGZAGBACKGROUNDMUSIC_B_WAV_LENGTH                            4591
#define ZIGZAGEND_WAV                                                 46
#define ZIGZAGEND_WAV_LENGTH                                          109
#define NINJABACKGROUND_WAV                                           50
#define NINJABACKGROUND_WAV_LENGTH                                    4947
#define NINJA_BUTTON_01_WAV                                           51
#define NINJA_BUTTON_01_WAV_LENGTH                                    50
#define NINJA_BUTTON_02_WAV                                           52
#define NINJA_BUTTON_02_WAV_LENGTH                                    50
#define NINJA_BUTTON_03_WAV                                           53
#define NINJA_BUTTON_03_WAV_LENGTH                                    50
#define NINJA_BUTTON_04_WAV                                           54
#define NINJA_BUTTON_04_WAV_LENGTH                                    50
#define NINJA_BUTTON_05_WAV                                           55
#define NINJA_BUTTON_05_WAV_LENGTH                                    50
#define NINJA_BUTTON_06_WAV                                           56
#define NINJA_BUTTON_06_WAV_LENGTH                                    50
#define NINJA_BUTTON_07_WAV                                           57
#define NINJA_BUTTON_07_WAV_LENGTH                                    50
#define NINJA_BUTTON_08_WAV                                           58
#define NINJA_BUTTON_08_WAV_LENGTH                                    50
#define NINJA_QUICKHIT_01_WAV                                         59
#define NINJA_QUICKHIT_01_WAV_LENGTH                                  26
#define NINJA_QUICKHIT_02_WAV                                         60
#define NINJA_QUICKHIT_02_WAV_LENGTH                                  23
#define NINJA_QUICKHIT_03_WAV                                         61
#define NINJA_QUICKHIT_03_WAV_LENGTH                                  23
#define NINJA_QUICKHIT_04_WAV                                         62
#define NINJA_QUICKHIT_04_WAV_LENGTH                                  25
#define NINJA_QUICKHIT_05_WAV                                         63
#define NINJA_QUICKHIT_05_WAV_LENGTH                                  30
#define NINJA_BIGHIT_01_WAV                                           64
#define NINJA_BIGHIT_01_WAV_LENGTH                                    166
#define NINJA_BIGHIT_02_WAV                                           65
#define NINJA_BIGHIT_02_WAV_LENGTH                                    80
#define NINJA_BIGHIT_03_WAV                                           66
#define NINJA_BIGHIT_03_WAV_LENGTH                                    159
#define NINJA_BIGHIT_04_WAV                                           67
#define NINJA_BIGHIT_04_WAV_LENGTH                                    93
#define NINJA_BIGHIT_05_WAV                                           68
#define NINJA_BIGHIT_05_WAV_LENGTH                                    156
#define NINJA_HUGEHIT_01_WAV                                          69
#define NINJA_HUGEHIT_01_WAV_LENGTH                                   78
#define NINJA_HUGEHIT_02_WAV                                          70
#define NINJA_HUGEHIT_02_WAV_LENGTH                                   81
#define NINJA_HUGEHIT_03_WAV                                          71
#define NINJA_HUGEHIT_03_WAV_LENGTH                                   78
#define NINJA_HUGEHIT_04_WAV                                          72
#define NINJA_HUGEHIT_04_WAV_LENGTH                                   66
#define NINJA_HUGEHIT_05_WAV                                          73
#define NINJA_HUGEHIT_05_WAV_LENGTH                                   194
#define NINJA_BADGONG_01_WAV                                          74
#define NINJA_BADGONG_01_WAV_LENGTH                                   147
#define RODEO_CRISSCROSS_01_WAV                                       80
#define RODEO_CRISSCROSS_01_WAV_LENGTH                                110
#define RODEO_SOLIDWALL_01_WAV                                        81
#define RODEO_SOLIDWALL_01_WAV_LENGTH                                 109
#define RODEO_TOPBOTTOM_01_WAV                                        82
#define RODEO_TOPBOTTOM_01_WAV_LENGTH                                 216
#define RODEOBACKGROUND_A_WAV                                         84
#define RODEOBACKGROUND_A_WAV_LENGTH                                  4691
#define RODEOBACKGROUND_B_WAV                                         85
#define RODEOBACKGROUND_B_WAV_LENGTH                                  4691
#define RODEOEND_WAV                                                  86
#define RODEOEND_WAV_LENGTH                                           105
#define MARATHON_INTRO_WAV                                            90
#define MARATHON_INTRO_WAV_LENGTH                                     457
#define MARATHON_LEVEL_FANFARE_WAV                                    91
#define MARATHON_LEVEL_FANFARE_WAV_LENGTH                             210
#define MARATHON_SECTION_1_WAV                                        92
#define MARATHON_SECTION_1_WAV_LENGTH                                 1371
#define MARATHON_SECTION_2_WAV                                        93
#define MARATHON_SECTION_2_WAV_LENGTH                                 1371
#define MARATHON_SECTION_3_WAV                                        94
#define MARATHON_SECTION_3_WAV_LENGTH                                 1371
#define MARATHON_SECTION_4_WAV                                        95
#define MARATHON_SECTION_4_WAV_LENGTH                                 1371
#define MARATHON_ENDING_FANFARE_WAV                                   96
#define MARATHON_ENDING_FANFARE_WAV_LENGTH                            279
#define MARATHON_JUMP_WAV                                             97
#define MARATHON_JUMP_WAV_LENGTH                                      25
#define MARATHON_HIT_WAV                                              98
#define MARATHON_HIT_WAV_LENGTH                                       11
#define BUZZER_WAV                                                    99
#define BUZZER_WAV_LENGTH                                             155
#define DDBACKGROUND_WAV                                              100
#define DDBACKGROUND_WAV_LENGTH                                       3918
#define DDBUTTONFX_WAV                                                101
#define DDBUTTONFX_WAV_LENGTH                                         1385
#define DDCORRECT_WAV                                                 102
#define DDCORRECT_WAV_LENGTH                                          94
#define DDINCORRECT_WAV                                               103
#define DDINCORRECT_WAV_LENGTH                                        14
#define DDEND_WAV                                                     104
#define DDEND_WAV_LENGTH                                              100
#define FF_BACKGROUND_WAV                                             110
#define FF_BACKGROUND_WAV_LENGTH                                      4896
#define FF_END_WAV                                                    111
#define FF_END_WAV_LENGTH                                             99
#define FIREFIGHTER_FIREAPPEAR_WAV                                    112
#define FIREFIGHTER_FIREAPPEAR_WAV_LENGTH                             96
#define FIREFIGHTER_FIREOUT_WAV                                       113
#define FIREFIGHTER_FIREOUT_WAV_LENGTH                                42
#define FIREFIGHTER_HIT_WAV                                           114
#define FIREFIGHTER_HIT_WAV_LENGTH                                    25
#define FIREFIGHTER_MISS_WAV                                          115
#define FIREFIGHTER_MISS_WAV_LENGTH                                   8
#define BUILDUP_A_WAV                                                 128
#define BUILDUP_A_WAV_LENGTH                                          1000
#define BUILDUP_B_WAV                                                 129
#define BUILDUP_B_WAV_LENGTH                                          1000
#define HEARTBEAT_WAV                                                 130
#define HEARTBEAT_WAV_LENGTH                                          234
#define GTR1A_WAV                                                     162
#define GTR1A_WAV_LENGTH                                              391
#define GTR1B_WAV                                                     163
#define GTR1B_WAV_LENGTH                                              242
#define GTR1C_WAV                                                     164
#define GTR1C_WAV_LENGTH                                              551
#define GTR2A_WAV                                                     165
#define GTR2A_WAV_LENGTH                                              404
#define GTR2B_WAV                                                     166
#define GTR2B_WAV_LENGTH                                              293
#define GTR2C_WAV                                                     167
#define GTR2C_WAV_LENGTH                                              391
#define GTR3A_WAV                                                     168
#define GTR3A_WAV_LENGTH                                              475
#define GTR3B_WAV                                                     169
#define GTR3B_WAV_LENGTH                                              491
#define ROCKBACKGROUND_WAV                                            174
#define ROCKBACKGROUND_WAV_LENGTH                                     4613

#endif
