#ifndef _SOUND_MAPPING_H
#define _SOUND_MAPPING_H


#define SELECTIONBUTTON_WAV                                           0
#define SELECTIONBUTTON_WAV_LENGTH                                    41
#define COUNTDOWN_WAV                                                 1
#define COUNTDOWN_WAV_LENGTH                                          254
#define BUTTONFEEDBACK_WAV                                            2
#define BUTTONFEEDBACK_WAV_LENGTH                                     62
#define ENDING_WAV                                                    3
#define ENDING_WAV_LENGTH                                             800
#define MAINTHEME_L_WAV                                               4
#define MAINTHEME_L_WAV_LENGTH                                        13217
#define MAINTHEME_R_WAV                                               5
#define MAINTHEME_R_WAV_LENGTH                                        13217
#define BUILDUP_A_WAV                                                 6
#define BUILDUP_A_WAV_LENGTH                                          1000
#define BUILDUP_B_WAV                                                 7
#define BUILDUP_B_WAV_LENGTH                                          1000
#define HEARTBEAT_WAV                                                 8
#define HEARTBEAT_WAV_LENGTH                                          234
#define NODE0_WAV                                                     10
#define NODE0_WAV_LENGTH                                              83
#define NODE1_WAV                                                     11
#define NODE1_WAV_LENGTH                                              45
#define NODE2_WAV                                                     12
#define NODE2_WAV_LENGTH                                              53
#define NODE3_WAV                                                     13
#define NODE3_WAV_LENGTH                                              47
#define NODE4_WAV                                                     14
#define NODE4_WAV_LENGTH                                              95
#define NODE5_WAV                                                     15
#define NODE5_WAV_LENGTH                                              77
#define NODE6_WAV                                                     16
#define NODE6_WAV_LENGTH                                              40
#define NODE7_WAV                                                     17
#define NODE7_WAV_LENGTH                                              97
#define BONUSSOUND_WAV                                                18
#define BONUSSOUND_WAV_LENGTH                                         80
#define LIGHTGRABBERBACKGROUNDMUSIC_WAV                               19
#define LIGHTGRABBERBACKGROUNDMUSIC_WAV_LENGTH                        4800
#define LIGHTGRABBERBACKGROUNDMUSIC_BONUS_WAV                         20
#define LIGHTGRABBERBACKGROUNDMUSIC_BONUS_WAV_LENGTH                  999
#define LG_END_WAV                                                    21
#define LG_END_WAV_LENGTH                                             65
#define BALL_SERVE_WAV                                                31
#define BALL_SERVE_WAV_LENGTH                                         68
#define BALL_HIT_WAV                                                  32
#define BALL_HIT_WAV_LENGTH                                           24
#define BALL_BOUNCE_WAV                                               33
#define BALL_BOUNCE_WAV_LENGTH                                        10
#define ZIGZAGSFX1_WAV                                                34
#define ZIGZAGSFX1_WAV_LENGTH                                         74
#define ZIGZAGSFX2_WAV                                                35
#define ZIGZAGSFX2_WAV_LENGTH                                         69
#define ZIGZAGSFX3_WAV                                                36
#define ZIGZAGSFX3_WAV_LENGTH                                         60
#define ZIGZAGSFX4_WAV                                                37
#define ZIGZAGSFX4_WAV_LENGTH                                         59
#define ZIGZAGSFX5_WAV                                                38
#define ZIGZAGSFX5_WAV_LENGTH                                         59
#define ZIGZAGSFX6_WAV                                                39
#define ZIGZAGSFX6_WAV_LENGTH                                         60
#define ZIGZAGSFX7_WAV                                                40
#define ZIGZAGSFX7_WAV_LENGTH                                         55
#define ZIGZAGSFX8_WAV                                                41
#define ZIGZAGSFX8_WAV_LENGTH                                         65
#define ZIGZAGSFX9_WAV                                                42
#define ZIGZAGSFX9_WAV_LENGTH                                         60
#define ZIGZAGSFX10_WAV                                               43
#define ZIGZAGSFX10_WAV_LENGTH                                        59
#define ZIGZAGBACKGROUNDMUSIC_A_WAV                                   44
#define ZIGZAGBACKGROUNDMUSIC_A_WAV_LENGTH                            4591
#define ZIGZAGBACKGROUNDMUSIC_B_WAV                                   45
#define ZIGZAGBACKGROUNDMUSIC_B_WAV_LENGTH                            4591
#define ZIGZAGEND_WAV                                                 46
#define ZIGZAGEND_WAV_LENGTH                                          109
#define BASS1A_WAV                                                    50
#define BASS1A_WAV_LENGTH                                             208
#define BASS1B_WAV                                                    51
#define BASS1B_WAV_LENGTH                                             274
#define BASS1C_WAV                                                    52
#define BASS1C_WAV_LENGTH                                             229
#define GTR1A_WAV                                                     62
#define GTR1A_WAV_LENGTH                                              391
#define GTR2A_WAV                                                     65
#define GTR2A_WAV_LENGTH                                              404
#define GTR3A_WAV                                                     68
#define GTR3A_WAV_LENGTH                                              475
#define GTR4A_WAV                                                     69
#define GTR4A_WAV_LENGTH                                              472
#define ROCKBACKGROUND_WAV                                            70
#define ROCKBACKGROUND_WAV_LENGTH                                     4613
#define DUCKCHASEMUSIC_WAV                                            80
#define DUCKCHASEMUSIC_WAV_LENGTH                                     133
#define DUCKHIT_WAV                                                   81
#define DUCKHIT_WAV_LENGTH                                            39
#define GOOSE_WAV                                                     82
#define GOOSE_WAV_LENGTH                                              52
#define GOOSECALL_WAV                                                 83
#define GOOSECALL_WAV_LENGTH                                          452
#define GOOSECHASEMUSIC_WAV                                           84
#define GOOSECHASEMUSIC_WAV_LENGTH                                    4119
#define GOOSEHIT_WAV                                                  85
#define GOOSEHIT_WAV_LENGTH                                           38
#define COMETBACKGROUND_WAV                                           90
#define COMETBACKGROUND_WAV_LENGTH                                    4500
#define LASERBLAST_WAV                                                91
#define LASERBLAST_WAV_LENGTH                                         120
#define MISS_WAV                                                      92
#define MISS_WAV_LENGTH                                               37
#define NEWCOMET_WAV                                                  93
#define NEWCOMET_WAV_LENGTH                                           50


#endif

