#ifndef _BOARD_SUPPORT_H
#define _BOARD_SUPPORT_H

#define BUTTON_LOCATION    		 0x0002
#define BUTTON_LOCATION_OLD	     0x0080


#define GREEN_LED_LOCATION 	0x02
#define RED_LED_LOCATION 	0x01

#define GREEN_LED_LOC		0x02
#define RED_LED_LOC			0x01


#define GREEN_LED_ON	LATD |= GREEN_LED_LOC
#define GREEN_LED_OFF	LATD &= ~GREEN_LED_LOC

#define RED_LED_ON		LATD |= RED_LED_LOC	
#define RED_LED_OFF		LATD &= ~RED_LED_LOC


#define MEM0_LOC		0x1000
#define MEM1_LOC		0x2000
#define MEM2_LOC		0x4000
#define MEM3_LOC		0x8000

#define OPTION0_LOC		0x0040
#define OPTION1_LOC		0x0080
#define OPTION2_LOC		0x0200
#define OPTION3_LOC		0x0400


#define MEM0_ENABLE LATA&=~MEM0_LOC;
#define MEM1_ENABLE LATA&=~MEM1_LOC;
#define MEM2_ENABLE LATA&=~MEM2_LOC;
#define MEM3_ENABLE LATA&=~MEM3_LOC;

#define MEM0_DISABLE LATA|=MEM0_LOC;
#define MEM1_DISABLE LATA|=MEM1_LOC;
#define MEM2_DISABLE LATA|=MEM2_LOC;
#define MEM3_DISABLE LATA|=MEM3_LOC;

#define CAN_TRANSCIEVER_ENABLE	LATB&=~CAN_HS_LOC
#define CAN_TRANSCIEVER_DISABLE	LATB|=CAN_HS_LOC

#define MEM_WRITE_ENABLE	LATB&=~CAN_HS_LOC
#define MEM_WRITE_DISABLE	LATB|=CAN_HS_LOC

#define VIN_SENSE_ANALOG		 0x0004
#define CAN_HS_LOC				 0x2000
#define VREG_ENABLE_LOC 	     0x4000
#define MEM_WRITE_LOC		     0x8000


#define GROUNDED_IO_LOC			 0x1000
#define AUDIO_SHUTDOWN_LOC		 0x0008
#define USB_RESET_LOC		 	 0x0001
#define USB_RESET_ENABLE	LATG&=~USB_RESET_LOC;
#define USB_RESET_DISABLE	LATG|=USB_RESET_LOC;


void PortInit(void);

#endif

