#ifndef __ERROR_CODES
#define __ERROR_CODES



#define PING_ERROR_BASE_CODE		100
#define POWER_ERROR_BASE_CODE		200
#define DATA_ERROR_BASE_CODE		300

#define NODE_ADDRESSING_ERROR		120

#define DIAGNOSTIC_PING_BASE_CODE	PING_ERROR_BASE_CODE
#define DIAGNOSTIC_POWER_BASE_CODE	POWER_ERROR_BASE_CODE
#define DIAGNOSTIC_DATA_BASE_CODE	 DATA_ERROR_BASE_CODE


#endif
