#ifndef _INTERNAL_BUTTON_SOUND_MAPPING_H
#define _INTERNAL_BUTTON_SOUND_MAPPING_H

#define INTERNAL_SOUND_POSITIVE_FEEDBACK	0
#define INTERNAL_SOUND_SELECTION			1
#define INTERNAL_SOUND_FF_WATER_HIT			2
#define INTERNAL_SOUND_FF_WATER_MISS		3
#define INTERNAL_SOUND_FF_FIRE_APPEAR		4
#define INTERNAL_SOUND_FF_FIRE_OUT			5


#endif 


