#include <p30fxxxx.h>

#ifndef _BOARDSUPPORT_H
#define _BOARDSUPPORT_H

#define BUTTON_LOCATION    		 0x0002
#define BUTTON_LOCATION_OLD	     0x0080

#define GROUNDED_IO_LOC			 0x1000
#define VIN_SENSE_ANALOG		 0x0004

#define GREEN_LED_LOCATION 	     0x0002
#define RED_LED_LOCATION 		 0x0001

#define AUDIO_SHUTDOWN_LOC		 0x0008
#define CAN_HS_LOC				 0x2000
#define VREG_ENABLE_LOC 	 	 0x4000


#define LED_RED    LEDOverride=TRUE;LATD|=RED_LED_LOCATION;LATD&=~GREEN_LED_LOCATION
#define LED_GREEN  LEDOverride=TRUE;LATD&=~RED_LED_LOCATION;LATD|=GREEN_LED_LOCATION
#define LED_YELLOW LEDOverride=TRUE;LATD|=RED_LED_LOCATION;LATD|=GREEN_LED_LOCATION
#define LED_OFF    LATD&=~RED_LED_LOCATION;LATD&=~GREEN_LED_LOCATION;LEDOverride=FALSE;

#define AUDIO_ENABLE	LATG&=~AUDIO_SHUTDOWN_LOC
#define AUDIO_DISABLE	LATG|=AUDIO_SHUTDOWN_LOC

#define CAN_TRANSCIEVER_ENABLE	LATB&=~CAN_HS_LOC
#define CAN_TRANSCIEVER_DISABLE	LATB|=CAN_HS_LOC

#define VOLTAGE_REGULATOR_ENABLE	LATB|=VREG_ENABLE_LOC
#define VOLTAGE_REGULATOR_DISABLE 	LATB&=~VREG_ENABLE_LOC


void PortInit(void);
void ReadOptionJumpers(void);
void RegulatorControl(void);
void ResetAll();


#endif

