#ifndef _SOUND_MAPPING_H
#define _SOUND_MAPPING_H


#define SELECTIONBUTTON_WAV                                           0
#define SELECTIONBUTTON_WAV_LENGTH                                    41
#define COUNTDOWN_WAV                                                 1
#define COUNTDOWN_WAV_LENGTH                                          254
#define BUTTONFEEDBACK_WAV                                            2
#define BUTTONFEEDBACK_WAV_LENGTH                                     62
#define ENDING_WAV                                                    3
#define ENDING_WAV_LENGTH                                             800
#define LIGHTRINGMAINTHEME_L_WAV                                      4
#define LIGHTRINGMAINTHEME_L_WAV_LENGTH                               12047
#define LIGHTRINGMAINTHEME_R_WAV                                      5
#define LIGHTRINGMAINTHEME_R_WAV_LENGTH                               12047
#define BUILDUP_A_WAV                                                 6
#define BUILDUP_A_WAV_LENGTH                                          1000
#define BUILDUP_B_WAV                                                 7
#define BUILDUP_B_WAV_LENGTH                                          1000
#define HEARTBEAT_WAV                                                 8
#define HEARTBEAT_WAV_LENGTH                                          234
#define NODE0_WAV                                                     10
#define NODE0_WAV_LENGTH                                              83
#define NODE1_WAV                                                     11
#define NODE1_WAV_LENGTH                                              45
#define NODE2_WAV                                                     12
#define NODE2_WAV_LENGTH                                              53
#define NODE3_WAV                                                     13
#define NODE3_WAV_LENGTH                                              47
#define NODE4_WAV                                                     14
#define NODE4_WAV_LENGTH                                              95
#define NODE5_WAV                                                     15
#define NODE5_WAV_LENGTH                                              77
#define NODE6_WAV                                                     16
#define NODE6_WAV_LENGTH                                              40
#define NODE7_WAV                                                     17
#define NODE7_WAV_LENGTH                                              97
#define BONUSSOUND_WAV                                                18
#define BONUSSOUND_WAV_LENGTH                                         80
#define LIGHTGRABBERBACKGROUNDMUSIC_WAV                               19
#define LIGHTGRABBERBACKGROUNDMUSIC_WAV_LENGTH                        4800
#define LIGHTGRABBERBACKGROUNDMUSIC_BONUS_WAV                         20
#define LIGHTGRABBERBACKGROUNDMUSIC_BONUS_WAV_LENGTH                  999
#define LG_END_WAV                                                    21
#define LG_END_WAV_LENGTH                                             65
#define BALL_SERVE_WAV                                                31
#define BALL_SERVE_WAV_LENGTH                                         68
#define BALL_HIT_WAV                                                  32
#define BALL_HIT_WAV_LENGTH                                           24
#define BALL_BOUNCE_WAV                                               33
#define BALL_BOUNCE_WAV_LENGTH                                        10
#define ZIGZAGSFX1_WAV                                                34
#define ZIGZAGSFX1_WAV_LENGTH                                         74
#define ZIGZAGSFX2_WAV                                                35
#define ZIGZAGSFX2_WAV_LENGTH                                         69
#define ZIGZAGSFX3_WAV                                                36
#define ZIGZAGSFX3_WAV_LENGTH                                         60
#define ZIGZAGSFX4_WAV                                                37
#define ZIGZAGSFX4_WAV_LENGTH                                         59
#define ZIGZAGSFX5_WAV                                                38
#define ZIGZAGSFX5_WAV_LENGTH                                         59
#define ZIGZAGSFX6_WAV                                                39
#define ZIGZAGSFX6_WAV_LENGTH                                         60
#define ZIGZAGSFX7_WAV                                                40
#define ZIGZAGSFX7_WAV_LENGTH                                         55
#define ZIGZAGSFX8_WAV                                                41
#define ZIGZAGSFX8_WAV_LENGTH                                         65
#define ZIGZAGSFX9_WAV                                                42
#define ZIGZAGSFX9_WAV_LENGTH                                         60
#define ZIGZAGSFX10_WAV                                               43
#define ZIGZAGSFX10_WAV_LENGTH                                        59
#define ZIGZAGBACKGROUNDMUSIC_A_WAV                                   44
#define ZIGZAGBACKGROUNDMUSIC_A_WAV_LENGTH                            4591
#define ZIGZAGBACKGROUNDMUSIC_B_WAV                                   45
#define ZIGZAGBACKGROUNDMUSIC_B_WAV_LENGTH                            4591
#define ZIGZAGEND_WAV                                                 46
#define ZIGZAGEND_WAV_LENGTH                                          109
#define BRASS1_WAV                                                    50
#define BRASS1_WAV_LENGTH                                             265
#define BRASS2_WAV                                                    51
#define BRASS2_WAV_LENGTH                                             299
#define BRASS3_WAV                                                    52
#define BRASS3_WAV_LENGTH                                             261
#define FLT1_WAV                                                      53
#define FLT1_WAV_LENGTH                                               219
#define FLT2_WAV                                                      54
#define FLT2_WAV_LENGTH                                               164
#define FLT3_WAV                                                      55
#define FLT3_WAV_LENGTH                                               243
#define GLOCK1_WAV                                                    56
#define GLOCK1_WAV_LENGTH                                             170
#define GLOCK2_WAV                                                    57
#define GLOCK2_WAV_LENGTH                                             236
#define GLOCK3_WAV                                                    58
#define GLOCK3_WAV_LENGTH                                             412
#define HARP1_WAV                                                     59
#define HARP1_WAV_LENGTH                                              290
#define HARP2_WAV                                                     60
#define HARP2_WAV_LENGTH                                              392
#define HARP3_WAV                                                     61
#define HARP3_WAV_LENGTH                                              351
#define PNO1_WAV                                                      62
#define PNO1_WAV_LENGTH                                               230
#define PNO2_WAV                                                      63
#define PNO2_WAV_LENGTH                                               287
#define PNO3_WAV                                                      64
#define PNO3_WAV_LENGTH                                               235
#define VLN1_WAV                                                      65
#define VLN1_WAV_LENGTH                                               288
#define VLN2_WAV                                                      66
#define VLN2_WAV_LENGTH                                               377
#define VLN3_WAV                                                      67
#define VLN3_WAV_LENGTH                                               240
#define JAMCIRCLEBACKGROUND_WAV                                       68
#define JAMCIRCLEBACKGROUND_WAV_LENGTH                                4721
#define DUCKCHASEMUSIC_WAV                                            80
#define DUCKCHASEMUSIC_WAV_LENGTH                                     133
#define DUCKHIT_WAV                                                   81
#define DUCKHIT_WAV_LENGTH                                            39
#define GOOSE_WAV                                                     82
#define GOOSE_WAV_LENGTH                                              52
#define GOOSECALL_WAV                                                 83
#define GOOSECALL_WAV_LENGTH                                          452
#define GOOSECHASEMUSIC_WAV                                           84
#define GOOSECHASEMUSIC_WAV_LENGTH                                    4119
#define GOOSEHIT_WAV                                                  85
#define GOOSEHIT_WAV_LENGTH                                           38
#define DUCKDUCK_BACKGROUND_NO_QUACKS_WAV                             86
#define DUCKDUCK_BACKGROUND_NO_QUACKS_WAV_LENGTH                      1073
#define DUCKDUCK_BACKGROUND_QUACKS_WAV                                87
#define DUCKDUCK_BACKGROUND_QUACKS_WAV_LENGTH                         1073
#define DUCKDUCK_BACKGROUND_GOOSE_QUACKS_WAV                          88
#define DUCKDUCK_BACKGROUND_GOOSE_QUACKS_WAV_LENGTH                   1073
#define DUCKDUCK_FULLCHASE_WAV                                        89
#define DUCKDUCK_FULLCHASE_WAV_LENGTH                                 1073
#define DUCKDUCK_FULLCHASE_NO_GOOSE_WAV                               90
#define DUCKDUCK_FULLCHASE_NO_GOOSE_WAV_LENGTH                        1073
#define DUCK_WAV                                                      91
#define DUCK_WAV_LENGTH                                               132
#define RINGSE0_WAV                                                   100
#define RINGSE0_WAV_LENGTH                                            27
#define RINGSE1_WAV                                                   101
#define RINGSE1_WAV_LENGTH                                            57
#define RINGSE2_WAV                                                   102
#define RINGSE2_WAV_LENGTH                                            42
#define RINGSE3_WAV                                                   103
#define RINGSE3_WAV_LENGTH                                            209
#define RINGSE4_WAV                                                   104
#define RINGSE4_WAV_LENGTH                                            159
#define RINGSE5_WAV                                                   105
#define RINGSE5_WAV_LENGTH                                            89
#define RINGSE6_WAV                                                   106
#define RINGSE6_WAV_LENGTH                                            109
#define RINGSE7_WAV                                                   107
#define RINGSE7_WAV_LENGTH                                            57
#define RINGSE8_WAV                                                   108
#define RINGSE8_WAV_LENGTH                                            405
#define RINGSE9_WAV                                                   109
#define RINGSE9_WAV_LENGTH                                            25
#define RINGSE10_WAV                                                  110
#define RINGSE10_WAV_LENGTH                                           42
#define RINGSE11_WAV                                                  111
#define RINGSE11_WAV_LENGTH                                           25
#define FLIPFLOPBACKGROUND_WAV                                        160
#define FLIPFLOPBACKGROUND_WAV_LENGTH                                 4438
#define FLOP1_WAV                                                     161
#define FLOP1_WAV_LENGTH                                              44
#define FLOP2_WAV                                                     162
#define FLOP2_WAV_LENGTH                                              45


#endif
