sox Belch.wav -b8 output\Belch.wav 
sox Button1.1.wav -b8 output\Button1.1.wav 
sox Button1.2.wav -b8 output\Button1.2.wav 
sox Button1.3.wav -b8 output\Button1.3.wav 
sox Button1.4.wav -b8 output\Button1.4.wav 
sox Button2.1.wav -b8 output\Button2.1.wav 
sox Button2.2.wav -b8 output\Button2.2.wav 
sox Button2.3.wav -b8 output\Button2.3.wav 
sox Button2.4.wav -b8 output\Button2.4.wav 
sox Button3.1.wav -b8 output\Button3.1.wav 
sox Button3.2.wav -b8 output\Button3.2.wav 
sox Button3.3.wav -b8 output\Button3.3.wav 
sox Button3.4.wav -b8 output\Button3.4.wav 
sox Button4.1.wav -b8 output\Button4.1.wav 
sox Button4.2.wav -b8 output\Button4.2.wav 
sox Button4.3.wav -b8 output\Button4.3.wav 
sox Button4.4.wav -b8 output\Button4.4.wav 
sox Fart.wav -b8 output\Fart.wav 
sox GameOver.wav -b8 output\GameOver.wav 
sox GetReady.wav -b8 output\GetReady.wav 
sox MagicMirrorWelcomeTack.wav -b8 output\MagicMirrorWelcomeTack.wav 
sox MM_FL_GETREADY_01A.wav -b8 output\MM_FL_GETREADY_01A.wav 
sox MM_FL_GETREADY_01B.wav -b8 output\MM_FL_GETREADY_01B.wav 
sox MM_FL_GETREADY_01C.wav -b8 output\MM_FL_GETREADY_01C.wav 
sox MM_FL_GETREADY_02A.wav -b8 output\MM_FL_GETREADY_02A.wav 
sox MM_FL_GETREADY_02B.wav -b8 output\MM_FL_GETREADY_02B.wav 
sox MM_FL_GETREADY_02C.wav -b8 output\MM_FL_GETREADY_02C.wav 
sox MM_FL_GETREADY_03A.wav -b8 output\MM_FL_GETREADY_03A.wav 
sox MM_FL_GETREADY_03B.wav -b8 output\MM_FL_GETREADY_03B.wav 
sox MM_FL_GETREADY_03C.wav -b8 output\MM_FL_GETREADY_03C.wav 
sox MM_FL_GETREADY_04A.wav -b8 output\MM_FL_GETREADY_04A.wav 
sox MM_FL_GETREADY_04B.wav -b8 output\MM_FL_GETREADY_04B.wav 
sox MM_FL_GETREADY_04C.wav -b8 output\MM_FL_GETREADY_04C.wav 
sox MM_FL_GETREADY_05A.wav -b8 output\MM_FL_GETREADY_05A.wav 
sox MM_FL_GETREADY_05B.wav -b8 output\MM_FL_GETREADY_05B.wav 
sox MM_FL_GETREADY_05C.wav -b8 output\MM_FL_GETREADY_05C.wav 
sox MM_FL_GETREADY_06A.wav -b8 output\MM_FL_GETREADY_06A.wav 
sox MM_FL_GETREADY_06B.wav -b8 output\MM_FL_GETREADY_06B.wav 
sox MM_FL_GETREADY_06C.wav -b8 output\MM_FL_GETREADY_06C.wav 
sox MM_FL_GETREADY_07A.wav -b8 output\MM_FL_GETREADY_07A.wav 
sox MM_FL_GETREADY_07B.wav -b8 output\MM_FL_GETREADY_07B.wav 
sox MM_FL_GETREADY_07C.wav -b8 output\MM_FL_GETREADY_07C.wav 
sox MM_FL_GETREADY_08A.wav -b8 output\MM_FL_GETREADY_08A.wav 
sox MM_FL_GETREADY_08B.wav -b8 output\MM_FL_GETREADY_08B.wav 
sox MM_FL_GETREADY_09A.wav -b8 output\MM_FL_GETREADY_09A.wav 
sox MM_FL_GETREADY_09B.wav -b8 output\MM_FL_GETREADY_09B.wav 
sox MM_FL_GETREADY_09C.wav -b8 output\MM_FL_GETREADY_09C.wav 
sox MM_FL_GETREADY_10A.wav -b8 output\MM_FL_GETREADY_10A.wav 
sox MM_FL_GETREADY_10B.wav -b8 output\MM_FL_GETREADY_10B.wav 
sox MM_FL_GETREADY_10C.wav -b8 output\MM_FL_GETREADY_10C.wav 
sox MM_FL_GETREADY_11A.wav -b8 output\MM_FL_GETREADY_11A.wav 
sox MM_FL_GETREADY_11B.wav -b8 output\MM_FL_GETREADY_11B.wav 
sox MM_FL_GETREADY_11C.wav -b8 output\MM_FL_GETREADY_11C.wav 
sox MM_FL_GETREADY_12A.wav -b8 output\MM_FL_GETREADY_12A.wav 
sox MM_FL_GETREADY_12B.wav -b8 output\MM_FL_GETREADY_12B.wav 
sox MM_FL_GETREADY_12C.wav -b8 output\MM_FL_GETREADY_12C.wav 
sox MM_FL_GETREADY_13A.wav -b8 output\MM_FL_GETREADY_13A.wav 
sox MM_FL_GETREADY_13B.wav -b8 output\MM_FL_GETREADY_13B.wav 
sox MM_FL_ONEMORE_01A.wav -b8 output\MM_FL_ONEMORE_01A.wav 
sox MM_FL_ONEMORE_01B.wav -b8 output\MM_FL_ONEMORE_01B.wav 
sox MM_FL_ONEMORE_01C.wav -b8 output\MM_FL_ONEMORE_01C.wav 
sox MM_FL_ONEMORE_02A.wav -b8 output\MM_FL_ONEMORE_02A.wav 
sox MM_FL_ONEMORE_02B.wav -b8 output\MM_FL_ONEMORE_02B.wav 
sox MM_FL_ONEMORE_02C.wav -b8 output\MM_FL_ONEMORE_02C.wav 
sox MM_FL_ONEMORE_03A.wav -b8 output\MM_FL_ONEMORE_03A.wav 
sox MM_FL_ONEMORE_03B.wav -b8 output\MM_FL_ONEMORE_03B.wav 
sox MM_FL_ONEMORE_03C.wav -b8 output\MM_FL_ONEMORE_03C.wav 
sox MM_FL_ONEMORE_04A.wav -b8 output\MM_FL_ONEMORE_04A.wav 
sox MM_FL_ONEMORE_04B.wav -b8 output\MM_FL_ONEMORE_04B.wav 
sox MM_FL_ONEMORE_04C.wav -b8 output\MM_FL_ONEMORE_04C.wav 
sox MM_FL_ONEMORE_05A.wav -b8 output\MM_FL_ONEMORE_05A.wav 
sox MM_FL_ONEMORE_05B.wav -b8 output\MM_FL_ONEMORE_05B.wav 
sox MM_FL_ONEMORE_05C.wav -b8 output\MM_FL_ONEMORE_05C.wav 
sox MM_FL_ONEMORE_06A.wav -b8 output\MM_FL_ONEMORE_06A.wav 
sox MM_FL_ONEMORE_06B.wav -b8 output\MM_FL_ONEMORE_06B.wav 
sox MM_FL_ONEMORE_06C.wav -b8 output\MM_FL_ONEMORE_06C.wav 
sox MM_FL_ONEMORE_07A.wav -b8 output\MM_FL_ONEMORE_07A.wav 
sox MM_FL_ONEMORE_07B.wav -b8 output\MM_FL_ONEMORE_07B.wav 
sox MM_FL_ONEMORE_07C.wav -b8 output\MM_FL_ONEMORE_07C.wav 
sox MM_FL_ONEMORE_08A.wav -b8 output\MM_FL_ONEMORE_08A.wav 
sox MM_FL_ONEMORE_08B.wav -b8 output\MM_FL_ONEMORE_08B.wav 
sox MM_FL_ONEMORE_08C.wav -b8 output\MM_FL_ONEMORE_08C.wav 
sox MM_FL_POSITIVE_01A.wav -b8 output\MM_FL_POSITIVE_01A.wav 
sox MM_FL_POSITIVE_01B.wav -b8 output\MM_FL_POSITIVE_01B.wav 
sox MM_FL_POSITIVE_01C.wav -b8 output\MM_FL_POSITIVE_01C.wav 
sox MM_FL_POSITIVE_02A.wav -b8 output\MM_FL_POSITIVE_02A.wav 
sox MM_FL_POSITIVE_02B.wav -b8 output\MM_FL_POSITIVE_02B.wav 
sox MM_FL_POSITIVE_02C.wav -b8 output\MM_FL_POSITIVE_02C.wav 
sox MM_FL_POSITIVE_03A.wav -b8 output\MM_FL_POSITIVE_03A.wav 
sox MM_FL_POSITIVE_03B.wav -b8 output\MM_FL_POSITIVE_03B.wav 
sox MM_FL_POSITIVE_03C.wav -b8 output\MM_FL_POSITIVE_03C.wav 
sox MM_FL_POSITIVE_04A.wav -b8 output\MM_FL_POSITIVE_04A.wav 
sox MM_FL_POSITIVE_04B.wav -b8 output\MM_FL_POSITIVE_04B.wav 
sox MM_FL_POSITIVE_04C.wav -b8 output\MM_FL_POSITIVE_04C.wav 
sox MM_FL_POSITIVE_05A.wav -b8 output\MM_FL_POSITIVE_05A.wav 
sox MM_FL_POSITIVE_05B.wav -b8 output\MM_FL_POSITIVE_05B.wav 
sox MM_FL_POSITIVE_05C.wav -b8 output\MM_FL_POSITIVE_05C.wav 
sox MM_FL_POSITIVE_05D.wav -b8 output\MM_FL_POSITIVE_05D.wav 
sox MM_FL_POSITIVE_06A.wav -b8 output\MM_FL_POSITIVE_06A.wav 
sox MM_FL_POSITIVE_06B.wav -b8 output\MM_FL_POSITIVE_06B.wav 
sox MM_FL_POSITIVE_06C.wav -b8 output\MM_FL_POSITIVE_06C.wav 
sox MM_FL_POSITIVE_07A.wav -b8 output\MM_FL_POSITIVE_07A.wav 
sox MM_FL_POSITIVE_07B.wav -b8 output\MM_FL_POSITIVE_07B.wav 
sox MM_FL_POSITIVE_07C.wav -b8 output\MM_FL_POSITIVE_07C.wav 
sox MM_FL_POSITIVE_08A.wav -b8 output\MM_FL_POSITIVE_08A.wav 
sox MM_FL_POSITIVE_08B.wav -b8 output\MM_FL_POSITIVE_08B.wav 
sox MM_FL_POSITIVE_08C.wav -b8 output\MM_FL_POSITIVE_08C.wav 
sox MM_FL_POSITIVE_09A.wav -b8 output\MM_FL_POSITIVE_09A.wav 
sox MM_FL_POSITIVE_09B.wav -b8 output\MM_FL_POSITIVE_09B.wav 
sox MM_FL_POSITIVE_10A.wav -b8 output\MM_FL_POSITIVE_10A.wav 
sox MM_FL_POSITIVE_10B.wav -b8 output\MM_FL_POSITIVE_10B.wav 
sox MM_FL_POSITIVE_10C.wav -b8 output\MM_FL_POSITIVE_10C.wav 
sox MM_FL_POSITIVE_11A.wav -b8 output\MM_FL_POSITIVE_11A.wav 
sox MM_FL_POSITIVE_11B.wav -b8 output\MM_FL_POSITIVE_11B.wav 
sox MM_FL_POSITIVE_11C.wav -b8 output\MM_FL_POSITIVE_11C.wav 
sox MM_FL_POSITIVE_12A.wav -b8 output\MM_FL_POSITIVE_12A.wav 
sox MM_FL_POSITIVE_12B.wav -b8 output\MM_FL_POSITIVE_12B.wav 
sox MM_FL_POSITIVE_12C.wav -b8 output\MM_FL_POSITIVE_12C.wav 
sox MM_FL_POSITIVE_13A.wav -b8 output\MM_FL_POSITIVE_13A.wav 
sox MM_FL_POSITIVE_13B.wav -b8 output\MM_FL_POSITIVE_13B.wav 
sox MM_FL_POSITIVE_13C.wav -b8 output\MM_FL_POSITIVE_13C.wav 
sox MM_FL_POSITIVE_14A.wav -b8 output\MM_FL_POSITIVE_14A.wav 
sox MM_FL_POSITIVE_14B.wav -b8 output\MM_FL_POSITIVE_14B.wav 
sox MM_FL_POSITIVE_14C.wav -b8 output\MM_FL_POSITIVE_14C.wav 
sox MM_FL_POSITIVE_15A.wav -b8 output\MM_FL_POSITIVE_15A.wav 
sox MM_FL_POSITIVE_15B.wav -b8 output\MM_FL_POSITIVE_15B.wav 
sox MM_FL_POSITIVE_15C.wav -b8 output\MM_FL_POSITIVE_15C.wav 
sox MM_FL_POSITIVE_16A.wav -b8 output\MM_FL_POSITIVE_16A.wav 
sox MM_FL_POSITIVE_16B.wav -b8 output\MM_FL_POSITIVE_16B.wav 
sox MM_FL_POSITIVE_16C.wav -b8 output\MM_FL_POSITIVE_16C.wav 
sox MM_FL_POSITIVE_17A.wav -b8 output\MM_FL_POSITIVE_17A.wav 
sox MM_FL_POSITIVE_17B.wav -b8 output\MM_FL_POSITIVE_17B.wav 
sox MM_FL_POSITIVE_17C.wav -b8 output\MM_FL_POSITIVE_17C.wav 
sox MM_FL_POSITIVE_18A.wav -b8 output\MM_FL_POSITIVE_18A.wav 
sox MM_FL_POSITIVE_18B.wav -b8 output\MM_FL_POSITIVE_18B.wav 
sox MM_FL_POSITIVE_18C.wav -b8 output\MM_FL_POSITIVE_18C.wav 
sox MM_FL_POSITIVE_19A.wav -b8 output\MM_FL_POSITIVE_19A.wav 
sox MM_FL_POSITIVE_19B.wav -b8 output\MM_FL_POSITIVE_19B.wav 
sox MM_FL_POSITIVE_19C.wav -b8 output\MM_FL_POSITIVE_19C.wav 
sox MM_FL_POSITIVE_20A.wav -b8 output\MM_FL_POSITIVE_20A.wav 
sox MM_FL_POSITIVE_20B.wav -b8 output\MM_FL_POSITIVE_20B.wav 
sox MM_FL_POSITIVE_20C.wav -b8 output\MM_FL_POSITIVE_20C.wav 
sox MM_FL_POSITIVE_21A.wav -b8 output\MM_FL_POSITIVE_21A.wav 
sox MM_FL_POSITIVE_21B.wav -b8 output\MM_FL_POSITIVE_21B.wav 
sox MM_FL_POSITIVE_22A.wav -b8 output\MM_FL_POSITIVE_22A.wav 
sox MM_FL_POSITIVE_22B.wav -b8 output\MM_FL_POSITIVE_22B.wav 
sox MM_FL_POSITIVE_22C.wav -b8 output\MM_FL_POSITIVE_22C.wav 
sox MM_FL_POSITIVE_23A.wav -b8 output\MM_FL_POSITIVE_23A.wav 
sox MM_FL_SENDOFF_01A.wav -b8 output\MM_FL_SENDOFF_01A.wav 
sox MM_FL_SENDOFF_01B.wav -b8 output\MM_FL_SENDOFF_01B.wav 
sox MM_FL_SENDOFF_01C.wav -b8 output\MM_FL_SENDOFF_01C.wav 
sox MM_FL_SENDOFF_02A.wav -b8 output\MM_FL_SENDOFF_02A.wav 
sox MM_FL_SENDOFF_02B.wav -b8 output\MM_FL_SENDOFF_02B.wav 
sox MM_FL_SENDOFF_02C.wav -b8 output\MM_FL_SENDOFF_02C.wav 
sox MM_FL_SENDOFF_03A.wav -b8 output\MM_FL_SENDOFF_03A.wav 
sox MM_FL_SENDOFF_03B.wav -b8 output\MM_FL_SENDOFF_03B.wav 
sox MM_FL_SENDOFF_03C.wav -b8 output\MM_FL_SENDOFF_03C.wav 
sox MM_FL_SENDOFF_04A.wav -b8 output\MM_FL_SENDOFF_04A.wav 
sox MM_FL_SENDOFF_04B.wav -b8 output\MM_FL_SENDOFF_04B.wav 
sox MM_FL_SENDOFF_04C.wav -b8 output\MM_FL_SENDOFF_04C.wav 
sox MM_FL_SENDOFF_05A.wav -b8 output\MM_FL_SENDOFF_05A.wav 
sox MM_FL_SENDOFF_05B.wav -b8 output\MM_FL_SENDOFF_05B.wav 
sox MM_FL_SENDOFF_05C.wav -b8 output\MM_FL_SENDOFF_05C.wav 
sox MM_FL_SENDOFF_05D.wav -b8 output\MM_FL_SENDOFF_05D.wav 
sox MM_FL_SENDOFF_06A.wav -b8 output\MM_FL_SENDOFF_06A.wav 
sox MM_FL_SENDOFF_06B.wav -b8 output\MM_FL_SENDOFF_06B.wav 
sox MM_FL_SENDOFF_06C.wav -b8 output\MM_FL_SENDOFF_06C.wav 
sox MM_FL_SENDOFF_07A.wav -b8 output\MM_FL_SENDOFF_07A.wav 
sox MM_FL_SENDOFF_07B.wav -b8 output\MM_FL_SENDOFF_07B.wav 
sox MM_FL_SENDOFF_07C.wav -b8 output\MM_FL_SENDOFF_07C.wav 
sox MM_FL_SENDOFF_07D.wav -b8 output\MM_FL_SENDOFF_07D.wav 
sox MM_FL_TWOMORE_01A.wav -b8 output\MM_FL_TWOMORE_01A.wav 
sox MM_FL_TWOMORE_01B.wav -b8 output\MM_FL_TWOMORE_01B.wav 
sox MM_FL_TWOMORE_01C.wav -b8 output\MM_FL_TWOMORE_01C.wav 
sox MM_FL_TWOMORE_02A.wav -b8 output\MM_FL_TWOMORE_02A.wav 
sox MM_FL_TWOMORE_02B.wav -b8 output\MM_FL_TWOMORE_02B.wav 
sox MM_FL_TWOMORE_02C.wav -b8 output\MM_FL_TWOMORE_02C.wav 
sox MM_FL_TWOMORE_03A.wav -b8 output\MM_FL_TWOMORE_03A.wav 
sox MM_FL_TWOMORE_03B.wav -b8 output\MM_FL_TWOMORE_03B.wav 
sox MM_FL_TWOMORE_03C.wav -b8 output\MM_FL_TWOMORE_03C.wav 
sox MM_FL_TWOMORE_04A.wav -b8 output\MM_FL_TWOMORE_04A.wav 
sox MM_FL_TWOMORE_04B.wav -b8 output\MM_FL_TWOMORE_04B.wav 
sox MM_FL_TWOMORE_04C.wav -b8 output\MM_FL_TWOMORE_04C.wav 
sox MM_FL_TWOMORE_05A.wav -b8 output\MM_FL_TWOMORE_05A.wav 
sox MM_FL_TWOMORE_05B.wav -b8 output\MM_FL_TWOMORE_05B.wav 
sox MM_FL_TWOMORE_05C.wav -b8 output\MM_FL_TWOMORE_05C.wav 
sox MM_FL_TWOMORE_06A.wav -b8 output\MM_FL_TWOMORE_06A.wav 
sox MM_FL_TWOMORE_06B.wav -b8 output\MM_FL_TWOMORE_06B.wav 
sox MM_FL_TWOMORE_06C.wav -b8 output\MM_FL_TWOMORE_06C.wav 
sox MM_FL_TWOMORE_07A.wav -b8 output\MM_FL_TWOMORE_07A.wav 
sox MM_FL_TWOMORE_07B.wav -b8 output\MM_FL_TWOMORE_07B.wav 
sox MM_FL_TWOMORE_07C.wav -b8 output\MM_FL_TWOMORE_07C.wav 
sox MM_FL_TWOMORE_08A.wav -b8 output\MM_FL_TWOMORE_08A.wav 
sox MM_FL_TWOMORE_08B.wav -b8 output\MM_FL_TWOMORE_08B.wav 
sox MM_FL_TWOMORE_08C.wav -b8 output\MM_FL_TWOMORE_08C.wav 
sox MM_FL_TWOMORE_09A.wav -b8 output\MM_FL_TWOMORE_09A.wav 
sox MM_FL_TWOMORE_09B.wav -b8 output\MM_FL_TWOMORE_09B.wav 
sox MM_FL_TWOMORE_09C.wav -b8 output\MM_FL_TWOMORE_09C.wav 
sox MM_FL_WELCOME_01A.wav -b8 output\MM_FL_WELCOME_01A.wav 
sox MM_FL_WELCOME_01B.wav -b8 output\MM_FL_WELCOME_01B.wav 
sox MM_FL_WELCOME_01C.wav -b8 output\MM_FL_WELCOME_01C.wav 
sox MM_FL_WELCOME_01D.wav -b8 output\MM_FL_WELCOME_01D.wav 
sox MM_FL_WELCOME_02B.wav -b8 output\MM_FL_WELCOME_02B.wav 
sox MM_FL_WELCOME_03A.wav -b8 output\MM_FL_WELCOME_03A.wav 
sox MM_FL_WELCOME_04B.wav -b8 output\MM_FL_WELCOME_04B.wav 
sox MM_FL_WELCOME_04C.wav -b8 output\MM_FL_WELCOME_04C.wav 
sox MM_FL_WELCOME_05A.wav -b8 output\MM_FL_WELCOME_05A.wav 
sox MM_FL_WELCOME_06A.wav -b8 output\MM_FL_WELCOME_06A.wav 
sox MM_FL_WELCOME_06B.wav -b8 output\MM_FL_WELCOME_06B.wav 
sox MM_FL_WELCOME_07A.wav -b8 output\MM_FL_WELCOME_07A.wav 
sox MM_FL_WELCOME_08A.wav -b8 output\MM_FL_WELCOME_08A.wav 
sox MM_FL_WELCOME_08B.wav -b8 output\MM_FL_WELCOME_08B.wav 
sox MM_FL_WELCOME_09A.wav -b8 output\MM_FL_WELCOME_09A.wav 
sox MM_FL_WELCOME_09B.wav -b8 output\MM_FL_WELCOME_09B.wav 
sox OneMoreChance.wav -b8 output\OneMoreChance.wav 
sox Station1_Idle.wav -b8 output\Station1_Idle.wav 
sox Station2_Idle.wav -b8 output\Station2_Idle.wav 
sox Station3_Idle.wav -b8 output\Station3_Idle.wav 
sox Station4_Idle.wav -b8 output\Station4_Idle.wav 
sox StationID_1.wav -b8 output\StationID_1.wav 
sox StationID_2.wav -b8 output\StationID_2.wav 
sox StationID_3.wav -b8 output\StationID_3.wav 
sox StationID_4.wav -b8 output\StationID_4.wav 
sox TwoMoreChances.wav -b8 output\TwoMoreChances.wav 
sox Win.wav -b8 output\Win.wav 
pause 
