#ifndef _SOUND_MAPPING_H
#define _SOUND_MAPPING_H


#define BUTTON1_1_WAV                                                 0
#define BUTTON1_1_WAV_LENGTH                                          226
#define BUTTON1_2_WAV                                                 1
#define BUTTON1_2_WAV_LENGTH                                          225
#define BUTTON1_3_WAV                                                 2
#define BUTTON1_3_WAV_LENGTH                                          226
#define BUTTON1_4_WAV                                                 3
#define BUTTON1_4_WAV_LENGTH                                          225
#define BUTTON2_1_WAV                                                 4
#define BUTTON2_1_WAV_LENGTH                                          236
#define BUTTON2_2_WAV                                                 5
#define BUTTON2_2_WAV_LENGTH                                          237
#define BUTTON2_3_WAV                                                 6
#define BUTTON2_3_WAV_LENGTH                                          237
#define BUTTON2_4_WAV                                                 7
#define BUTTON2_4_WAV_LENGTH                                          238
#define BUTTON3_1_WAV                                                 8
#define BUTTON3_1_WAV_LENGTH                                          301
#define BUTTON3_2_WAV                                                 9
#define BUTTON3_2_WAV_LENGTH                                          301
#define BUTTON3_3_WAV                                                 10
#define BUTTON3_3_WAV_LENGTH                                          301
#define BUTTON3_4_WAV                                                 11
#define BUTTON3_4_WAV_LENGTH                                          301
#define BUTTON4_1_WAV                                                 12
#define BUTTON4_1_WAV_LENGTH                                          401
#define BUTTON4_2_WAV                                                 13
#define BUTTON4_2_WAV_LENGTH                                          402
#define BUTTON4_3_WAV                                                 14
#define BUTTON4_3_WAV_LENGTH                                          401
#define BUTTON4_4_WAV                                                 15
#define BUTTON4_4_WAV_LENGTH                                          401
#define BELCH_WAV                                                     16
#define BELCH_WAV_LENGTH                                              78
#define FART_WAV                                                      17
#define FART_WAV_LENGTH                                               125
#define GETREADY_WAV                                                  18
#define GETREADY_WAV_LENGTH                                           157
#define MAGICMIRRORWELCOMETRACK_WAV                                   19
#define MAGICMIRRORWELCOMETRACK_WAV_LENGTH                            199
#define ONEMORECHANCE_WAV                                             20
#define ONEMORECHANCE_WAV_LENGTH                                      115
#define POSTIVECOMMENT_WAV                                            21
#define POSTIVECOMMENT_WAV_LENGTH                                     400
#define SENDOFF_WAV                                                   23
#define SENDOFF_WAV_LENGTH                                            75
#define STATION1_IDLE_WAV                                             24
#define STATION1_IDLE_WAV_LENGTH                                      2317
#define STATION2_IDLE_WAV                                             25
#define STATION2_IDLE_WAV_LENGTH                                      2750
#define STATION3_IDLE_WAV                                             26
#define STATION3_IDLE_WAV_LENGTH                                      3273
#define STATION4_IDLE_WAV                                             27
#define STATION4_IDLE_WAV_LENGTH                                      3773
#define STATIONID_1_WAV                                               28
#define STATIONID_1_WAV_LENGTH                                        141
#define STATIONID_2_WAV                                               29
#define STATIONID_2_WAV_LENGTH                                        132
#define STATIONID_3_WAV                                               30
#define STATIONID_3_WAV_LENGTH                                        140
#define STATIONID_4_WAV                                               31
#define STATIONID_4_WAV_LENGTH                                        138
#define TWOMORECHANCES_WAV                                            32
#define TWOMORECHANCES_WAV_LENGTH                                     143
#define WIN_WAV                                                       33
#define WIN_WAV_LENGTH                                                112
#define MM_FL_WELCOME_01A_WAV                                         34
#define MM_FL_WELCOME_01A_WAV_LENGTH                                  1064
#define MM_FL_WELCOME_01B_WAV                                         35
#define MM_FL_WELCOME_01B_WAV_LENGTH                                  1221
#define MM_FL_WELCOME_01C_WAV                                         36
#define MM_FL_WELCOME_01C_WAV_LENGTH                                  1344
#define MM_FL_WELCOME_01D_WAV                                         37
#define MM_FL_WELCOME_01D_WAV_LENGTH                                  1211
#define MM_FL_WELCOME_02B_WAV                                         38
#define MM_FL_WELCOME_02B_WAV_LENGTH                                  1121
#define MM_FL_WELCOME_03A_WAV                                         39
#define MM_FL_WELCOME_03A_WAV_LENGTH                                  1848
#define MM_FL_WELCOME_04B_WAV                                         40
#define MM_FL_WELCOME_04B_WAV_LENGTH                                  1761
#define MM_FL_WELCOME_04C_WAV                                         41
#define MM_FL_WELCOME_04C_WAV_LENGTH                                  1868
#define MM_FL_WELCOME_05A_WAV                                         42
#define MM_FL_WELCOME_05A_WAV_LENGTH                                  2108
#define MM_FL_WELCOME_06A_WAV                                         43
#define MM_FL_WELCOME_06A_WAV_LENGTH                                  2108
#define MM_FL_WELCOME_07A_WAV                                         44
#define MM_FL_WELCOME_07A_WAV_LENGTH                                  2082
#define MM_FL_WELCOME_08B_WAV                                         45
#define MM_FL_WELCOME_08B_WAV_LENGTH                                  1995
#define MM_FL_WELCOME_09A_WAV                                         46
#define MM_FL_WELCOME_09A_WAV_LENGTH                                  2409
#define MM_FL_WELCOME_09B_WAV                                         47
#define MM_FL_WELCOME_09B_WAV_LENGTH                                  2535
#define MM_FL_GETREADY_01A_WAV                                        48
#define MM_FL_GETREADY_01A_WAV_LENGTH                                 210
#define MM_FL_GETREADY_01B_WAV                                        49
#define MM_FL_GETREADY_01B_WAV_LENGTH                                 216
#define MM_FL_GETREADY_01C_WAV                                        50
#define MM_FL_GETREADY_01C_WAV_LENGTH                                 233
#define MM_FL_GETREADY_02A_WAV                                        51
#define MM_FL_GETREADY_02A_WAV_LENGTH                                 296
#define MM_FL_GETREADY_02B_WAV                                        52
#define MM_FL_GETREADY_02B_WAV_LENGTH                                 263
#define MM_FL_GETREADY_02C_WAV                                        53
#define MM_FL_GETREADY_02C_WAV_LENGTH                                 253
#define MM_FL_GETREADY_03A_WAV                                        54
#define MM_FL_GETREADY_03A_WAV_LENGTH                                 153
#define MM_FL_GETREADY_03B_WAV                                        55
#define MM_FL_GETREADY_03B_WAV_LENGTH                                 123
#define MM_FL_GETREADY_03C_WAV                                        56
#define MM_FL_GETREADY_03C_WAV_LENGTH                                 136
#define MM_FL_GETREADY_04A_WAV                                        57
#define MM_FL_GETREADY_04A_WAV_LENGTH                                 204
#define MM_FL_GETREADY_04B_WAV                                        58
#define MM_FL_GETREADY_04B_WAV_LENGTH                                 160
#define MM_FL_GETREADY_04C_WAV                                        59
#define MM_FL_GETREADY_04C_WAV_LENGTH                                 260
#define MM_FL_GETREADY_05A_WAV                                        60
#define MM_FL_GETREADY_05A_WAV_LENGTH                                 423
#define MM_FL_GETREADY_05B_WAV                                        61
#define MM_FL_GETREADY_05B_WAV_LENGTH                                 530
#define MM_FL_GETREADY_05C_WAV                                        62
#define MM_FL_GETREADY_05C_WAV_LENGTH                                 283
#define MM_FL_GETREADY_06A_WAV                                        63
#define MM_FL_GETREADY_06A_WAV_LENGTH                                 463
#define MM_FL_GETREADY_06B_WAV                                        64
#define MM_FL_GETREADY_06B_WAV_LENGTH                                 547
#define MM_FL_GETREADY_06C_WAV                                        65
#define MM_FL_GETREADY_06C_WAV_LENGTH                                 520
#define MM_FL_GETREADY_07A_WAV                                        66
#define MM_FL_GETREADY_07A_WAV_LENGTH                                 410
#define MM_FL_GETREADY_07B_WAV                                        67
#define MM_FL_GETREADY_07B_WAV_LENGTH                                 413
#define MM_FL_GETREADY_07C_WAV                                        68
#define MM_FL_GETREADY_07C_WAV_LENGTH                                 541
#define MM_FL_GETREADY_08A_WAV                                        69
#define MM_FL_GETREADY_08A_WAV_LENGTH                                 670
#define MM_FL_GETREADY_08B_WAV                                        70
#define MM_FL_GETREADY_08B_WAV_LENGTH                                 657
#define MM_FL_GETREADY_09A_WAV                                        71
#define MM_FL_GETREADY_09A_WAV_LENGTH                                 567
#define MM_FL_GETREADY_09B_WAV                                        72
#define MM_FL_GETREADY_09B_WAV_LENGTH                                 707
#define MM_FL_GETREADY_09C_WAV                                        73
#define MM_FL_GETREADY_09C_WAV_LENGTH                                 760
#define MM_FL_GETREADY_10A_WAV                                        74
#define MM_FL_GETREADY_10A_WAV_LENGTH                                 226
#define MM_FL_GETREADY_10B_WAV                                        75
#define MM_FL_GETREADY_10B_WAV_LENGTH                                 296
#define MM_FL_GETREADY_10C_WAV                                        76
#define MM_FL_GETREADY_10C_WAV_LENGTH                                 216
#define MM_FL_GETREADY_11A_WAV                                        77
#define MM_FL_GETREADY_11A_WAV_LENGTH                                 260
#define MM_FL_GETREADY_11B_WAV                                        78
#define MM_FL_GETREADY_11B_WAV_LENGTH                                 487
#define MM_FL_GETREADY_11C_WAV                                        79
#define MM_FL_GETREADY_11C_WAV_LENGTH                                 430
#define MM_FL_GETREADY_12A_WAV                                        80
#define MM_FL_GETREADY_12A_WAV_LENGTH                                 460
#define MM_FL_GETREADY_12B_WAV                                        81
#define MM_FL_GETREADY_12B_WAV_LENGTH                                 700
#define MM_FL_GETREADY_12C_WAV                                        82
#define MM_FL_GETREADY_12C_WAV_LENGTH                                 487
#define MM_FL_GETREADY_13A_WAV                                        83
#define MM_FL_GETREADY_13A_WAV_LENGTH                                 840
#define MM_FL_GETREADY_13B_WAV                                        84
#define MM_FL_GETREADY_13B_WAV_LENGTH                                 627
#define MM_FL_POSITIVE_01A_WAV                                        85
#define MM_FL_POSITIVE_01A_WAV_LENGTH                                 216
#define MM_FL_POSITIVE_01B_WAV                                        86
#define MM_FL_POSITIVE_01B_WAV_LENGTH                                 186
#define MM_FL_POSITIVE_01C_WAV                                        87
#define MM_FL_POSITIVE_01C_WAV_LENGTH                                 280
#define MM_FL_POSITIVE_02A_WAV                                        88
#define MM_FL_POSITIVE_02A_WAV_LENGTH                                 226
#define MM_FL_POSITIVE_02B_WAV                                        89
#define MM_FL_POSITIVE_02B_WAV_LENGTH                                 226
#define MM_FL_POSITIVE_02C_WAV                                        90
#define MM_FL_POSITIVE_02C_WAV_LENGTH                                 253
#define MM_FL_POSITIVE_03A_WAV                                        91
#define MM_FL_POSITIVE_03A_WAV_LENGTH                                 173
#define MM_FL_POSITIVE_03B_WAV                                        92
#define MM_FL_POSITIVE_03B_WAV_LENGTH                                 90
#define MM_FL_POSITIVE_03C_WAV                                        93
#define MM_FL_POSITIVE_03C_WAV_LENGTH                                 170
#define MM_FL_POSITIVE_04A_WAV                                        94
#define MM_FL_POSITIVE_04A_WAV_LENGTH                                 353
#define MM_FL_POSITIVE_04B_WAV                                        95
#define MM_FL_POSITIVE_04B_WAV_LENGTH                                 296
#define MM_FL_POSITIVE_04C_WAV                                        96
#define MM_FL_POSITIVE_04C_WAV_LENGTH                                 240
#define MM_FL_POSITIVE_05A_WAV                                        97
#define MM_FL_POSITIVE_05A_WAV_LENGTH                                 123
#define MM_FL_POSITIVE_05B_WAV                                        98
#define MM_FL_POSITIVE_05B_WAV_LENGTH                                 103
#define MM_FL_POSITIVE_05C_WAV                                        99
#define MM_FL_POSITIVE_05C_WAV_LENGTH                                 123
#define MM_FL_POSITIVE_05D_WAV                                        100
#define MM_FL_POSITIVE_05D_WAV_LENGTH                                 153
#define MM_FL_POSITIVE_06A_WAV                                        101
#define MM_FL_POSITIVE_06A_WAV_LENGTH                                 243
#define MM_FL_POSITIVE_06B_WAV                                        102
#define MM_FL_POSITIVE_06B_WAV_LENGTH                                 210
#define MM_FL_POSITIVE_06C_WAV                                        103
#define MM_FL_POSITIVE_06C_WAV_LENGTH                                 183
#define MM_FL_POSITIVE_07A_WAV                                        104
#define MM_FL_POSITIVE_07A_WAV_LENGTH                                 246
#define MM_FL_POSITIVE_07B_WAV                                        105
#define MM_FL_POSITIVE_07B_WAV_LENGTH                                 290
#define MM_FL_POSITIVE_07C_WAV                                        106
#define MM_FL_POSITIVE_07C_WAV_LENGTH                                 360
#define MM_FL_POSITIVE_08A_WAV                                        107
#define MM_FL_POSITIVE_08A_WAV_LENGTH                                 333
#define MM_FL_POSITIVE_08B_WAV                                        108
#define MM_FL_POSITIVE_08B_WAV_LENGTH                                 427
#define MM_FL_POSITIVE_08C_WAV                                        109
#define MM_FL_POSITIVE_08C_WAV_LENGTH                                 477
#define MM_FL_POSITIVE_09A_WAV                                        110
#define MM_FL_POSITIVE_09A_WAV_LENGTH                                 123
#define MM_FL_POSITIVE_09B_WAV                                        111
#define MM_FL_POSITIVE_09B_WAV_LENGTH                                 153
#define MM_FL_POSITIVE_10A_WAV                                        112
#define MM_FL_POSITIVE_10A_WAV_LENGTH                                 150
#define MM_FL_POSITIVE_10B_WAV                                        113
#define MM_FL_POSITIVE_10B_WAV_LENGTH                                 186
#define MM_FL_POSITIVE_10C_WAV                                        114
#define MM_FL_POSITIVE_10C_WAV_LENGTH                                 156
#define MM_FL_POSITIVE_11A_WAV                                        115
#define MM_FL_POSITIVE_11A_WAV_LENGTH                                 236
#define MM_FL_POSITIVE_11B_WAV                                        116
#define MM_FL_POSITIVE_11B_WAV_LENGTH                                 163
#define MM_FL_POSITIVE_11C_WAV                                        117
#define MM_FL_POSITIVE_11C_WAV_LENGTH                                 300
#define MM_FL_POSITIVE_12A_WAV                                        118
#define MM_FL_POSITIVE_12A_WAV_LENGTH                                 300
#define MM_FL_POSITIVE_12B_WAV                                        119
#define MM_FL_POSITIVE_12B_WAV_LENGTH                                 270
#define MM_FL_POSITIVE_12C_WAV                                        120
#define MM_FL_POSITIVE_12C_WAV_LENGTH                                 316
#define MM_FL_POSITIVE_13A_WAV                                        121
#define MM_FL_POSITIVE_13A_WAV_LENGTH                                 286
#define MM_FL_POSITIVE_13B_WAV                                        122
#define MM_FL_POSITIVE_13B_WAV_LENGTH                                 280
#define MM_FL_POSITIVE_13C_WAV                                        123
#define MM_FL_POSITIVE_13C_WAV_LENGTH                                 206
#define MM_FL_POSITIVE_14A_WAV                                        124
#define MM_FL_POSITIVE_14A_WAV_LENGTH                                 240
#define MM_FL_POSITIVE_14B_WAV                                        125
#define MM_FL_POSITIVE_14B_WAV_LENGTH                                 176
#define MM_FL_POSITIVE_14C_WAV                                        126
#define MM_FL_POSITIVE_14C_WAV_LENGTH                                 246
#define MM_FL_POSITIVE_15A_WAV                                        127
#define MM_FL_POSITIVE_15A_WAV_LENGTH                                 123
#define MM_FL_POSITIVE_15B_WAV                                        128
#define MM_FL_POSITIVE_15B_WAV_LENGTH                                 200
#define MM_FL_POSITIVE_15C_WAV                                        129
#define MM_FL_POSITIVE_15C_WAV_LENGTH                                 163
#define MM_FL_POSITIVE_16A_WAV                                        130
#define MM_FL_POSITIVE_16A_WAV_LENGTH                                 290
#define MM_FL_POSITIVE_16B_WAV                                        131
#define MM_FL_POSITIVE_16B_WAV_LENGTH                                 360
#define MM_FL_POSITIVE_16C_WAV                                        132
#define MM_FL_POSITIVE_16C_WAV_LENGTH                                 330
#define MM_FL_POSITIVE_17A_WAV                                        133
#define MM_FL_POSITIVE_17A_WAV_LENGTH                                 293
#define MM_FL_POSITIVE_17B_WAV                                        134
#define MM_FL_POSITIVE_17B_WAV_LENGTH                                 306
#define MM_FL_POSITIVE_17C_WAV                                        135
#define MM_FL_POSITIVE_17C_WAV_LENGTH                                 166
#define MM_FL_POSITIVE_18A_WAV                                        136
#define MM_FL_POSITIVE_18A_WAV_LENGTH                                 283
#define MM_FL_POSITIVE_18B_WAV                                        137
#define MM_FL_POSITIVE_18B_WAV_LENGTH                                 183
#define MM_FL_POSITIVE_18C_WAV                                        138
#define MM_FL_POSITIVE_18C_WAV_LENGTH                                 130
#define MM_FL_POSITIVE_19A_WAV                                        139
#define MM_FL_POSITIVE_19A_WAV_LENGTH                                 226
#define MM_FL_POSITIVE_19B_WAV                                        140
#define MM_FL_POSITIVE_19B_WAV_LENGTH                                 160
#define MM_FL_POSITIVE_19C_WAV                                        141
#define MM_FL_POSITIVE_19C_WAV_LENGTH                                 223
#define MM_FL_POSITIVE_20A_WAV                                        142
#define MM_FL_POSITIVE_20A_WAV_LENGTH                                 153
#define MM_FL_POSITIVE_20B_WAV                                        143
#define MM_FL_POSITIVE_20B_WAV_LENGTH                                 110
#define MM_FL_POSITIVE_20C_WAV                                        144
#define MM_FL_POSITIVE_20C_WAV_LENGTH                                 96
#define MM_FL_POSITIVE_21A_WAV                                        145
#define MM_FL_POSITIVE_21A_WAV_LENGTH                                 410
#define MM_FL_POSITIVE_21B_WAV                                        146
#define MM_FL_POSITIVE_21B_WAV_LENGTH                                 296
#define MM_FL_POSITIVE_22A_WAV                                        147
#define MM_FL_POSITIVE_22A_WAV_LENGTH                                 280
#define MM_FL_POSITIVE_22B_WAV                                        148
#define MM_FL_POSITIVE_22B_WAV_LENGTH                                 230
#define MM_FL_POSITIVE_22C_WAV                                        149
#define MM_FL_POSITIVE_22C_WAV_LENGTH                                 226
#define MM_FL_POSITIVE_23A_WAV                                        150
#define MM_FL_POSITIVE_23A_WAV_LENGTH                                 423
#define MM_FL_TWOMORE_01A_WAV                                         151
#define MM_FL_TWOMORE_01A_WAV_LENGTH                                  296
#define MM_FL_TWOMORE_01B_WAV                                         152
#define MM_FL_TWOMORE_01B_WAV_LENGTH                                  283
#define MM_FL_TWOMORE_01C_WAV                                         153
#define MM_FL_TWOMORE_01C_WAV_LENGTH                                  310
#define MM_FL_TWOMORE_02A_WAV                                         154
#define MM_FL_TWOMORE_02A_WAV_LENGTH                                  383
#define MM_FL_TWOMORE_02B_WAV                                         155
#define MM_FL_TWOMORE_02B_WAV_LENGTH                                  323
#define MM_FL_TWOMORE_02C_WAV                                         156
#define MM_FL_TWOMORE_02C_WAV_LENGTH                                  320
#define MM_FL_TWOMORE_03A_WAV                                         157
#define MM_FL_TWOMORE_03A_WAV_LENGTH                                  387
#define MM_FL_TWOMORE_03B_WAV                                         158
#define MM_FL_TWOMORE_03B_WAV_LENGTH                                  467
#define MM_FL_TWOMORE_03C_WAV                                         159
#define MM_FL_TWOMORE_03C_WAV_LENGTH                                  377
#define MM_FL_TWOMORE_04A_WAV                                         160
#define MM_FL_TWOMORE_04A_WAV_LENGTH                                  383
#define MM_FL_TWOMORE_04B_WAV                                         161
#define MM_FL_TWOMORE_04B_WAV_LENGTH                                  473
#define MM_FL_TWOMORE_04C_WAV                                         162
#define MM_FL_TWOMORE_04C_WAV_LENGTH                                  337
#define MM_FL_TWOMORE_05A_WAV                                         163
#define MM_FL_TWOMORE_05A_WAV_LENGTH                                  397
#define MM_FL_TWOMORE_05B_WAV                                         164
#define MM_FL_TWOMORE_05B_WAV_LENGTH                                  313
#define MM_FL_TWOMORE_05C_WAV                                         165
#define MM_FL_TWOMORE_05C_WAV_LENGTH                                  300
#define MM_FL_TWOMORE_06A_WAV                                         166
#define MM_FL_TWOMORE_06A_WAV_LENGTH                                  543
#define MM_FL_TWOMORE_06B_WAV                                         167
#define MM_FL_TWOMORE_06B_WAV_LENGTH                                  567
#define MM_FL_TWOMORE_06C_WAV                                         168
#define MM_FL_TWOMORE_06C_WAV_LENGTH                                  557
#define MM_FL_TWOMORE_07A_WAV                                         169
#define MM_FL_TWOMORE_07A_WAV_LENGTH                                  413
#define MM_FL_TWOMORE_07B_WAV                                         170
#define MM_FL_TWOMORE_07B_WAV_LENGTH                                  483
#define MM_FL_TWOMORE_07C_WAV                                         171
#define MM_FL_TWOMORE_07C_WAV_LENGTH                                  373
#define MM_FL_TWOMORE_08A_WAV                                         172
#define MM_FL_TWOMORE_08A_WAV_LENGTH                                  503
#define MM_FL_TWOMORE_08B_WAV                                         173
#define MM_FL_TWOMORE_08B_WAV_LENGTH                                  430
#define MM_FL_TWOMORE_08C_WAV                                         174
#define MM_FL_TWOMORE_08C_WAV_LENGTH                                  737
#define MM_FL_ONEMORE_01A_WAV                                         175
#define MM_FL_ONEMORE_01A_WAV_LENGTH                                  453
#define MM_FL_ONEMORE_01B_WAV                                         176
#define MM_FL_ONEMORE_01B_WAV_LENGTH                                  383
#define MM_FL_ONEMORE_01C_WAV                                         177
#define MM_FL_ONEMORE_01C_WAV_LENGTH                                  480
#define MM_FL_ONEMORE_02A_WAV                                         178
#define MM_FL_ONEMORE_02A_WAV_LENGTH                                  286
#define MM_FL_ONEMORE_02B_WAV                                         179
#define MM_FL_ONEMORE_02B_WAV_LENGTH                                  246
#define MM_FL_ONEMORE_02C_WAV                                         180
#define MM_FL_ONEMORE_02C_WAV_LENGTH                                  296
#define MM_FL_ONEMORE_03A_WAV                                         181
#define MM_FL_ONEMORE_03A_WAV_LENGTH                                  550
#define MM_FL_ONEMORE_03B_WAV                                         182
#define MM_FL_ONEMORE_03B_WAV_LENGTH                                  473
#define MM_FL_ONEMORE_03C_WAV                                         183
#define MM_FL_ONEMORE_03C_WAV_LENGTH                                  610
#define MM_FL_ONEMORE_04A_WAV                                         184
#define MM_FL_ONEMORE_04A_WAV_LENGTH                                  437
#define MM_FL_ONEMORE_04B_WAV                                         185
#define MM_FL_ONEMORE_04B_WAV_LENGTH                                  377
#define MM_FL_ONEMORE_04C_WAV                                         186
#define MM_FL_ONEMORE_04C_WAV_LENGTH                                  557
#define MM_FL_ONEMORE_05A_WAV                                         187
#define MM_FL_ONEMORE_05A_WAV_LENGTH                                  170
#define MM_FL_ONEMORE_05B_WAV                                         188
#define MM_FL_ONEMORE_05B_WAV_LENGTH                                  120
#define MM_FL_ONEMORE_05C_WAV                                         189
#define MM_FL_ONEMORE_05C_WAV_LENGTH                                  136
#define MM_FL_ONEMORE_06A_WAV                                         190
#define MM_FL_ONEMORE_06A_WAV_LENGTH                                  547
#define MM_FL_ONEMORE_06B_WAV                                         191
#define MM_FL_ONEMORE_06B_WAV_LENGTH                                  493
#define MM_FL_ONEMORE_06C_WAV                                         192
#define MM_FL_ONEMORE_06C_WAV_LENGTH                                  603
#define MM_FL_ONEMORE_07A_WAV                                         193
#define MM_FL_ONEMORE_07A_WAV_LENGTH                                  420
#define MM_FL_ONEMORE_07B_WAV                                         194
#define MM_FL_ONEMORE_07B_WAV_LENGTH                                  330
#define MM_FL_ONEMORE_07C_WAV                                         195
#define MM_FL_ONEMORE_07C_WAV_LENGTH                                  367
#define MM_FL_ONEMORE_08A_WAV                                         196
#define MM_FL_ONEMORE_08A_WAV_LENGTH                                  433
#define MM_FL_ONEMORE_08B_WAV                                         197
#define MM_FL_ONEMORE_08B_WAV_LENGTH                                  533
#define MM_FL_ONEMORE_08C_WAV                                         198
#define MM_FL_ONEMORE_08C_WAV_LENGTH                                  503
#define MM_FL_SENDOFF_01A_WAV                                         199
#define MM_FL_SENDOFF_01A_WAV_LENGTH                                  503
#define MM_FL_SENDOFF_01B_WAV                                         200
#define MM_FL_SENDOFF_01B_WAV_LENGTH                                  460
#define MM_FL_SENDOFF_01C_WAV                                         201
#define MM_FL_SENDOFF_01C_WAV_LENGTH                                  560
#define MM_FL_SENDOFF_02A_WAV                                         202
#define MM_FL_SENDOFF_02A_WAV_LENGTH                                  487
#define MM_FL_SENDOFF_02B_WAV                                         203
#define MM_FL_SENDOFF_02B_WAV_LENGTH                                  477
#define MM_FL_SENDOFF_02C_WAV                                         204
#define MM_FL_SENDOFF_02C_WAV_LENGTH                                  557
#define MM_FL_SENDOFF_03A_WAV                                         205
#define MM_FL_SENDOFF_03A_WAV_LENGTH                                  541
#define MM_FL_SENDOFF_03B_WAV                                         206
#define MM_FL_SENDOFF_03B_WAV_LENGTH                                  667
#define MM_FL_SENDOFF_03C_WAV                                         207
#define MM_FL_SENDOFF_03C_WAV_LENGTH                                  583
#define MM_FL_SENDOFF_04A_WAV                                         208
#define MM_FL_SENDOFF_04A_WAV_LENGTH                                  600
#define MM_FL_SENDOFF_04B_WAV                                         209
#define MM_FL_SENDOFF_04B_WAV_LENGTH                                  547
#define MM_FL_SENDOFF_04C_WAV                                         210
#define MM_FL_SENDOFF_04C_WAV_LENGTH                                  670
#define MM_FL_SENDOFF_05A_WAV                                         211
#define MM_FL_SENDOFF_05A_WAV_LENGTH                                  460
#define MM_FL_SENDOFF_05B_WAV                                         212
#define MM_FL_SENDOFF_05B_WAV_LENGTH                                  517
#define MM_FL_SENDOFF_05C_WAV                                         213
#define MM_FL_SENDOFF_05C_WAV_LENGTH                                  590
#define MM_FL_SENDOFF_05D_WAV                                         214
#define MM_FL_SENDOFF_05D_WAV_LENGTH                                  680
#define MM_FL_SENDOFF_06A_WAV                                         215
#define MM_FL_SENDOFF_06A_WAV_LENGTH                                  440
#define MM_FL_SENDOFF_06B_WAV                                         216
#define MM_FL_SENDOFF_06B_WAV_LENGTH                                  513
#define MM_FL_SENDOFF_06C_WAV                                         217
#define MM_FL_SENDOFF_06C_WAV_LENGTH                                  620
#define MM_FL_SENDOFF_07A_WAV                                         218
#define MM_FL_SENDOFF_07A_WAV_LENGTH                                  934
#define MM_FL_SENDOFF_07B_WAV                                         219
#define MM_FL_SENDOFF_07B_WAV_LENGTH                                  997
#define MM_FL_SENDOFF_07C_WAV                                         220
#define MM_FL_SENDOFF_07C_WAV_LENGTH                                  924
#define MM_FL_SENDOFF_07D_WAV                                         221
#define MM_FL_SENDOFF_07D_WAV_LENGTH                                  970


#endif
